#pragma once

#include <Blackframe/Backends/GPU/CUDA/SceneBvh.hpp>
#include <Blackframe/Core/Status.hpp>
#include <Blackframe/Renderer/LightSampler.hpp>
#include <Blackframe/Renderer/MisHeuristics.hpp>
#include <Blackframe/Renderer/PathDepthLimits.hpp>
#include <Blackframe/Renderer/PathState.hpp>
#include <Blackframe/Renderer/Ray.hpp>
#include <Blackframe/Renderer/RussianRoulette.hpp>
#include <Blackframe/Renderer/SampleStream.hpp>
#include <Blackframe/XPU/CUDA/DeviceMemory.hpp>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <optional>
#include <span>
#include <type_traits>
#include <vector>

namespace blackframe::engine {

inline constexpr std::uint32_t CurrentCudaWavefrontTransportReportSchemaVersion = 2U;

struct CudaWavefrontPathInput final {
    renderer::Ray primary_ray;
    renderer::PathState initial_state;
    renderer::SampleStreamIndex sample;
};

enum class CudaWavefrontPathTermination : std::uint8_t {
    escaped_environment = 0U,
    depth_limit = 1U,
    zero_throughput = 2U,
    outside_bsdf_support = 3U,
    russian_roulette = 4U,
};

struct CudaWavefrontPathResult final {
    renderer::PathState state;
    renderer::Ray terminal_ray;
    CudaWavefrontPathTermination termination{};
    renderer::ScatteringLobe blocked_depth_limits{renderer::ScatteringLobe::none};
};

struct CudaWavefrontStageLaneCounts final {
    std::uint64_t camera{};
    std::uint64_t intersection{};
    std::uint64_t hit{};
    std::uint64_t miss{};
    std::uint64_t shade{};
    std::uint64_t shadow{};
    std::uint64_t continuation{};

    [[nodiscard]] constexpr bool
    operator==(const CudaWavefrontStageLaneCounts&) const noexcept = default;
};

struct CudaWavefrontTransportReport final {
    std::uint32_t schema_version{};
    bool has_light_sampler{};
    std::uint32_t registered_light_count{};
    renderer::MisHeuristic heuristic{renderer::MisHeuristic::power};
    renderer::LightSamplingStrategy light_sampling_strategy{
        renderer::LightSamplingStrategy::uniform};
    renderer::PathDepthLimits depth_limits{};
    renderer::RussianRoulettePolicy roulette_policy{renderer::RussianRoulettePolicy::disabled()};
    std::size_t path_count{};
    CudaWavefrontStageLaneCounts stage_lanes{};
    std::uint64_t closure_samples{};
    std::uint64_t light_samples{};
    std::uint64_t shadow_queries{};
    std::uint64_t terminated_paths{};
    std::uint64_t queue_overflow_attempts{};
    std::uint64_t queue_rejected_lanes{};

    [[nodiscard]] constexpr bool
    operator==(const CudaWavefrontTransportReport&) const noexcept = default;
};

struct CudaWavefrontTransportBatch final {
    std::vector<CudaWavefrontPathResult> paths;
    CudaWavefrontTransportReport report;
};

struct CudaWavefrontTransportOptions final {
    renderer::MisHeuristic heuristic{renderer::MisHeuristic::power};
    renderer::PathDepthLimits depth_limits{.diffuse = 5U};
    renderer::RussianRoulettePolicy roulette_policy{renderer::RussianRoulettePolicy::disabled()};
    xpu::cuda::DeviceMemoryBudget device_memory_budget{};
};

using CudaWavefrontLightSampler =
    std::optional<std::reference_wrapper<const renderer::LightSampler>>;

// Executes the currently representable FrameScene transport with explicit CUDA kernels and the
// serialized CUDA BLAS/TLAS. Inputs are primary rays and indexed sample addresses generated by the
// renderer contracts. The camera stage initializes device path streams from those immutable
// inputs; every later physical stage remains on the selected CUDA device. The initial CUDA port is
// deliberately limited to vacuum, spectral Lambertian materials, one-sided emission, the current
// punctual and mesh-area light registry, an explicitly uniform light sampler, balance or power
// MIS, and a constant environment. The sampler must be absent for an empty registry and present for
// a non-empty registry. Unsupported scene or path capabilities are rejected explicitly and are
// never substituted by a CPU backend.
[[nodiscard]] core::Result<CudaWavefrontTransportBatch>
trace_cuda_wavefront_transport(const CudaSceneSoA& scene, const CudaSceneBvh& bvh,
                               std::span<const CudaWavefrontPathInput> inputs,
                               CudaWavefrontLightSampler light_sampler,
                               CudaWavefrontTransportOptions options = {});

static_assert(std::is_standard_layout_v<CudaWavefrontPathInput>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontPathInput>);
static_assert(sizeof(CudaWavefrontPathTermination) == sizeof(std::uint8_t));
static_assert(std::is_standard_layout_v<CudaWavefrontStageLaneCounts>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontStageLaneCounts>);
static_assert(std::is_standard_layout_v<CudaWavefrontTransportReport>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontTransportReport>);
static_assert(std::is_standard_layout_v<CudaWavefrontTransportOptions>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontTransportOptions>);

} // namespace blackframe::engine
