#pragma once

#include <Blackframe/Backends/GPU/CUDA/SceneBvh.hpp>
#include <Blackframe/Core/Status.hpp>
#include <Blackframe/Renderer/PathState.hpp>
#include <Blackframe/Renderer/Ray.hpp>
#include <Blackframe/Renderer/SampleStream.hpp>
#include <Blackframe/XPU/CUDA/DeviceMemory.hpp>
#include <cstddef>
#include <cstdint>
#include <span>
#include <type_traits>
#include <vector>

namespace blackframe::engine {

inline constexpr std::uint32_t CurrentCudaWavefrontTransportReportSchemaVersion = 1U;

struct CudaWavefrontPathInput final {
    renderer::Ray primary_ray;
    renderer::PathState initial_state;
    renderer::SampleStreamIndex sample;
};

enum class CudaWavefrontPathTermination : std::uint8_t {
    escaped_environment = 0U,
    depth_limit = 1U,
    zero_throughput = 2U,
    outside_bsdf_support = 3U,
};

struct CudaWavefrontPathResult final {
    renderer::PathState state;
    renderer::Ray terminal_ray;
    CudaWavefrontPathTermination termination{};
};

struct CudaWavefrontStageLaneCounts final {
    std::uint64_t camera{};
    std::uint64_t intersection{};
    std::uint64_t hit{};
    std::uint64_t miss{};
    std::uint64_t shade{};
    std::uint64_t shadow{};
    std::uint64_t continuation{};

    [[nodiscard]] constexpr bool
    operator==(const CudaWavefrontStageLaneCounts&) const noexcept = default;
};

struct CudaWavefrontTransportReport final {
    std::uint32_t schema_version{};
    std::uint32_t maximum_diffuse_depth{};
    std::size_t path_count{};
    CudaWavefrontStageLaneCounts stage_lanes{};
    std::uint64_t light_samples{};
    std::uint64_t shadow_queries{};
    std::uint64_t terminated_paths{};
    std::uint64_t queue_overflow_attempts{};
    std::uint64_t queue_rejected_lanes{};

    [[nodiscard]] constexpr bool
    operator==(const CudaWavefrontTransportReport&) const noexcept = default;
};

struct CudaWavefrontTransportBatch final {
    std::vector<CudaWavefrontPathResult> paths;
    CudaWavefrontTransportReport report;
};

struct CudaWavefrontTransportOptions final {
    std::uint32_t maximum_diffuse_depth{5U};
    xpu::cuda::DeviceMemoryBudget device_memory_budget{};
};

// Executes the currently representable FrameScene transport with explicit CUDA kernels and the
// serialized CUDA BLAS/TLAS. Inputs are primary rays and indexed sample addresses generated by the
// renderer contracts. The camera stage initializes device path streams from those immutable
// inputs; every later physical stage remains on the selected CUDA device. The initial CUDA port is
// deliberately limited to vacuum, spectral Lambertian materials, one-sided mesh-area emission,
// uniform mesh-area next-event estimation, and a constant environment. Unsupported scene or path
// capabilities are rejected explicitly and are never substituted by a CPU backend.
[[nodiscard]] core::Result<CudaWavefrontTransportBatch>
trace_cuda_wavefront_transport(const CudaSceneSoA& scene, const CudaSceneBvh& bvh,
                               std::span<const CudaWavefrontPathInput> inputs,
                               CudaWavefrontTransportOptions options = {});

static_assert(std::is_standard_layout_v<CudaWavefrontPathInput>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontPathInput>);
static_assert(sizeof(CudaWavefrontPathTermination) == sizeof(std::uint8_t));
static_assert(std::is_standard_layout_v<CudaWavefrontStageLaneCounts>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontStageLaneCounts>);
static_assert(std::is_standard_layout_v<CudaWavefrontTransportReport>);
static_assert(std::is_trivially_copyable_v<CudaWavefrontTransportReport>);
static_assert(std::is_standard_layout_v<CudaWavefrontTransportOptions>);

} // namespace blackframe::engine
